---
title: "D607 Wk07 HW - Web APIs"
author: "Kyle Gilde"
date: "April 1, 2017"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

#The Task
The New York Times web site provides a rich set of APIs, as described here: http://developer.nytimes.com/docs

You'll need to start by signing up for an API key.

Your task is to choose one of the New York Times APIs, construct an interface in R to read in the JSON data, and transform it to an R dataframe.

#Load Packages
```{r setup, echo = FALSE} 
knitr::opts_chunk$set(warning=FALSE, 
                      message=FALSE,
                      tidy=TRUE
                      )

#create vector with all needed packages
load_packages <- c("prettydoc", "jsonlite", "knitr")

#see if we need to install any of them
install_load <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE, quietly = TRUE)
}

install_load(load_packages)
#CODE SOURCE DOCUMENTATION: https://gist.github.com/stevenworthington/3178163
```

#API Call
##The top 20 most viewed articles in the last 30 days
```{r}
base_uri <- "https://api.nytimes.com/svc/mostpopular/v2/"
popularity_metric <- "mostviewed/"
section <- "all-sections/"
time_period <- "30.json"
api_key <- "?api-key=016f630b0da546b796d27ee0f9bc3255"

url <- paste0(base_uri, popularity_metric, section, time_period, api_key)
my_results <- fromJSON(url)

my_df <- data.frame(my_results$results)

kable(my_df[,c(4:9,13)], caption = "Here are the results.")
```
